name: ci
run-name: ${{ github.actor }} pushed some code
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: chmod +x ${GITHUB_WORKSPACE}/ci/run_ci.sh && ${GITHUB_WORKSPACE}/ci/run_ci.sh